### ISSUE TITLE
Multi-dimensional arrays are not supported by the TMBuilder

### ISSUE THREAD

**Issue by yarg0007** [eBay/NSTSuite#41]
The path generated for multi-dimensional arrays is not valid for the JSON path field.

Expected: `$.path.message[*][*].text`
Actual: `$.path.message[*].message[*].text`

OpenAPI schema for multi-dimensional array:

```yaml
            message:
              type: array
              items:
                type: array
                items:
                  type: string
```
